spring.application.name=robloxmusic
# CONFIGURACIÓN DE BASE DE DATOS (MySQL)
# Asegúrate de crear la base de datos en MySQL con el comando: CREATE DATABASE robloxdb;
spring.datasource.url=jdbc:mysql://localhost:3306/robloxdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# 'update' crea las tablas automáticamente si no existen en tu MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CONFIGURACIÓN DE LOGS (Se mantiene guardando en archivo)
logging.level.root=INFO
logging.level.com.duoc.robloxmusic=DEBUG
logging.file.name=logs/robloxmusic.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n