spring.application.name=vrk
# CONFIGURACIÓN DE BASE DE DATOS (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/vrk?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CONFIGURACIÓN DE LOGS
logging.level.root=INFO
logging.level.com.duoc.vrk=DEBUG
logging.file.name=logs/vrk.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n